### PR TITLE
PR Templates Test

### PR DESCRIPTION
**Pull request by xklob**
# PR Type: Feature|Bug|Release

# PR Title: A Fancy Title Here Please

## PR Checklist - Feature (Proposal)

- [ ] All Tests Passing
- [ ] Proposal Added to ProposalsConfig
- [ ] Fork Block Correct
- [ ] Remove Any .only's on Tests
- [ ] Update Documentation If Needed
- [ ] Update Roles Config
- [ ] Proposal Submitted

## PR Checklist - Feature (Non-Proposal) | Bug

- [ ] All Tests Passing
- [ ] Remove Any .only's on Tests

## PR Checklist - Release

- [ ] All Tests Passing
- [ ] Clean/Empty Proposals Config
- [ ] Update Fork Block
- [ ] Update Docs If Needed

### CODE REVIEW

**Comment by Joeysantoro** [comment]
Update documentation should be a bit more specific imo. At minimum, new roles and mainnet addresses deployments should be kept up to date. Probably contract abis too.

**Comment by xklob** [comment]
> Update documentation should be a bit more specific imo. At minimum, new roles and mainnet addresses deployments should be kept up to date. Probably contract abis too.

@Joeysantoro wdym by contract abis - is there a place we should be updating them?

**Comment by sslivkoff** [comment]
probably want an entry in the checklist related to collateralization oracle updates

**Comment by Joeysantoro** [comment]
1. Add CR oracle updates
2. Link project/issue
3. Remove title/simplify description field
4. Deploy contract update/mainnet addresses/verify
5. remove .only or add a bot

**Pull request closed without merging**
